### ISSUE TITLE
Add @RegisterForReflection to POJOS

### ISSUE THREAD

**Issue by cchacin** [cchacin/MicroGen#282]

**Comment by sreejit123** [comment]
@cchacin Could you add more description? Is it on the same lines that Quarkus has to annotate classes/fields/methods of POJOs so that the VM does not remove them as unused when they are invoked via reflection?

**Comment by cchacin** [comment]
That is correct, **Quarkus** need that in order to generate the required Json files used for graalvm to generates the native code that uses to reflection for AOT.

**Comment by sreejit123** [comment]
@cchacin Created a PR for this: https://github.com/cchacin/MicroGen/pull/311 
Updated tests and README.md as well

**Comment by cchacin** [comment]
Thanks a lot @sreejit123 I'll review that today 🤘🏽
